workspace:
  base: /var/www/owncloud
  path: phoenix

branches: [master, release*, develop*]

pipeline:
  build-docker-image:
    image: toolhippie/docker:latest
    pull: true
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - docker build -t owncloud/phoenix:${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER} .

  install-server:
    image: owncloudci/core
    version: ${OC_VERSION=daily-master-qa}
    pull: true
    db_type: ${DB_TYPE=sqlite}
    db_name: ${DB_NAME=sqlite}
    db_host: ${DB_TYPE=sqlite}
    db_username: autotest
    db_password: owncloud
    core_path: /var/www/owncloud/

  clone-oauth:
    image: owncloud/ubuntu:16.04
    pull: true
    commands:
      - git clone -b master https://github.com/owncloud/oauth2.git /var/www/owncloud/apps/oauth2

  configure-server:
    image: owncloudci/php:${PHP_VERSION=7.1}
    pull: true
    commands:
      - cd /var/www/owncloud/
      - php occ a:e testing
      - php occ config:system:set trusted_domains 1 --value=owncloud
      - php occ config:system:set cors.allowed-domains 0 --value=http://phoenix:8300
      - php occ log:manage --level 0
      - php occ config:list
      - php occ a:e oauth2
      - php occ oauth2:add-client Phoenix Cxfj9F9ZZWQbQZps1E1M0BszMz6OOFq3lxjSuc8Uh4HLEYb9KIfyRMmgY5ibXXrU 930C6aA0U1VhM03IfNiheR2EwSzRi4hRSpcNqIhhbpeSGU6h38xssVfNcGP0sSwQ http://phoenix:8300/#/oidc-callback

  owncloud-log:
    image: owncloud/ubuntu:16.04
    detach: true
    pull: true
    commands:
      - tail -f /var/www/owncloud/data/owncloud.log

  wait-for-phoenix:
    image: owncloudci/php:${PHP_VERSION=7.1}
    pull: true
    commands:
      - wait-for-it -t 300 phoenix:8300

  fix-permissions:
    image: owncloudci/php:${PHP_VERSION=7.1}
    pull: true
    commands:
      - cd /var/www/owncloud/
      - chown www-data * -R

  webui-acceptance-tests:
    image: owncloudci/php:${PHP_VERSION=7.1}
    pull: true
    commands:
      - cd /var/www/owncloud/phoenix
      - yarn run acceptance-tests-drone

  lint-test:
    image: owncloudci/php:${PHP_VERSION=7.1}
    pull: true
    commands:
      - cd /var/www/owncloud/phoenix
      - yarn run lint

  build-release:
    image: owncloudci/php:${PHP_VERSION=7.1}
    pull: true
    commands:
      - cd /var/www/owncloud/phoenix
      - make -f Makefile.release dist

  deploy-staging:
    image: drillster/drone-rsync:latest
    pull: true
    secrets: [ rsync_key ]
    user: deploy
    hosts: pixie.owncloud.systems
    port: 22
    recursive: true
    delete: true
    source: dist/
    target: /home/deploy/phoenix
    script:
      - sudo docker exec phoenix occ maintenance:mode --on
      - sudo rsync -az --chown=www-data:www-data -r --del --exclude config.json /home/deploy/phoenix/ /var/lib/phoenix/apps/phoenix
      - sudo docker exec phoenix occ maintenance:mode --off
      - sudo docker exec phoenix owncloud migrate
    when:
      event: [ push ]
      branch: [ master ]

services:
  phoenix:
    image: owncloudci/php:${PHP_VERSION=7.1}
    pull: true
    commands:
      - git clone https://github.com/owncloud/owncloud-design-system.git
      - cd owncloud-design-system
      - yarn install && yarn build:system
      - cd ..
      - yarn install
      - yarn dist
      - cp tests/drone/config.json dist/config.json
      - make run SERVER_HOST=phoenix:8300

  owncloud:
    image: owncloudci/php:${PHP_VERSION=7.1}
    pull: true
    environment:
      - APACHE_WEBROOT=/var/www/owncloud/
    command: [ "/usr/local/bin/apachectl", "-e", "debug", "-D", "FOREGROUND" ]

  selenium:
    image: selenium/standalone-chrome-debug:latest
    pull: true

  docker:
    image: docker:18.04-dind
